# Generated by Django 6.0.8 on 2026-09-14 22:33

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Meu espaço', max_length=80, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'espaço',
                'verbose_name_plural': 'espaços',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('is_visitante', models.BooleanField(default=False, verbose_name='é visitante')),
                ('ultimo_acesso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='último acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('espaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='accounts.espaco', verbose_name='espaço')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConviteEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=accounts.models.gerar_codigo, max_length=12, unique=True, verbose_name='código')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_criados', to=settings.AUTH_USER_MODEL)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='accounts.espaco')),
            ],
            options={
                'verbose_name': 'convite',
                'verbose_name_plural': 'convites',
            },
        ),
        migrations.CreateModel(
            name='ConsumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60, verbose_name='modelo')),
                ('tokens_entrada', models.PositiveIntegerField(default=0, verbose_name='tokens de entrada')),
                ('tokens_saida', models.PositiveIntegerField(default=0, verbose_name='tokens de saída')),
                ('tokens_cache_escrita', models.PositiveIntegerField(default=0, verbose_name='tokens gravados em cache')),
                ('tokens_cache_leitura', models.PositiveIntegerField(default=0, verbose_name='tokens lidos do cache')),
                ('custo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='custo (USD)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consumo de IA',
                'verbose_name_plural': 'consumos de IA',
                'indexes': [models.Index(fields=['usuario', 'criado_em'], name='accounts_co_usuario_da0030_idx')],
            },
        ),
    ]
