# Generated by Django 6.0.8 on 2026-09-14 22:33

import carteira.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='emoji')),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita'), ('transferencia', 'Transferência')], default='despesa', max_length=20, verbose_name='tipo')),
                ('fixa', models.BooleanField(default=False, verbose_name='é gasto fixo')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='accounts.espaco')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('corrente', 'Conta corrente'), ('poupanca', 'Poupança'), ('cartao', 'Cartão de crédito'), ('dinheiro', 'Dinheiro')], default='corrente', max_length=20, verbose_name='tipo')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='saldo inicial')),
                ('dia_fechamento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dia de fechamento')),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dia de vencimento')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='accounts.espaco')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
            },
        ),
        migrations.CreateModel(
            name='Limite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(blank=True, max_length=60, verbose_name='rótulo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='carteira.categoria')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='accounts.espaco')),
            ],
            options={
                'verbose_name': 'limite',
                'verbose_name_plural': 'limites',
            },
        ),
        migrations.CreateModel(
            name='Recorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=140, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita'), ('transferencia', 'Transferência')], max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('dia_do_mes', models.PositiveSmallIntegerField(verbose_name='dia do mês')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorrentes', to='carteira.categoria')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorrentes', to='carteira.conta')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrentes', to='accounts.espaco')),
            ],
            options={
                'verbose_name': 'recorrente',
                'verbose_name_plural': 'recorrentes',
                'ordering': ['dia_do_mes'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=carteira.models.gerar_codigo_transacao, max_length=8, unique=True, verbose_name='código')),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita'), ('transferencia', 'Transferência')], max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('descricao', models.CharField(max_length=140, verbose_name='descrição')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('pago', models.BooleanField(default=True, verbose_name='pago')),
                ('origem', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio'), ('imagem', 'Imagem'), ('pdf', 'PDF'), ('portal', 'Portal'), ('recorrente', 'Recorrente')], default='portal', max_length=20, verbose_name='origem')),
                ('prevista', models.BooleanField(default=False, verbose_name='prevista')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='carteira.categoria')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='carteira.conta')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='carteira.conta')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='accounts.espaco')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-data', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('limite_proximo', 'Limite próximo'), ('limite_estourado', 'Limite estourado'), ('vencimento', 'Vencimento'), ('resumo', 'Resumo')], max_length=30, verbose_name='tipo')),
                ('chave', models.CharField(max_length=80, verbose_name='chave')),
                ('referencia', models.CharField(max_length=12, verbose_name='referência')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('adiado', models.BooleanField(default=False, verbose_name='adiado')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='accounts.espaco')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'constraints': [models.UniqueConstraint(fields=('espaco', 'tipo', 'chave', 'referencia'), name='alerta_unico_por_periodo')],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('espaco', 'nome'), name='categoria_unica_por_espaco'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(fields=('espaco', 'nome'), name='conta_unica_por_espaco'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['espaco', 'data'], name='carteira_tr_espaco__75d871_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['espaco', 'categoria', 'data'], name='carteira_tr_espaco__8a4575_idx'),
        ),
    ]
