# Generated by Django 6.0.8 on 2026-09-15 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carteira', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrente',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recorrente',
            name='compartilhada',
            field=models.BooleanField(default=True, verbose_name='compartilhada'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='compartilhada',
            field=models.BooleanField(default=True, verbose_name='compartilhada'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['espaco', 'compartilhada', 'autor'], name='carteira_tr_espaco__33c7e5_idx'),
        ),
    ]
