# Generated by Django 6.0.8 on 2026-09-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_recorrente_autor_recorrente_compartilhada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrente',
            name='compartilhada',
            field=models.BooleanField(default=False, verbose_name='compartilhada'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='compartilhada',
            field=models.BooleanField(default=False, verbose_name='compartilhada'),
        ),
    ]
