# Generated by Django 6.0.8 on 2026-09-15 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_alter_recorrente_compartilhada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='pago por'),
        ),
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to=settings.AUTH_USER_MODEL)),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='carteira.transacao')),
            ],
            options={
                'verbose_name': 'rateio',
                'verbose_name_plural': 'rateios',
                'constraints': [models.UniqueConstraint(fields=('transacao', 'pessoa'), name='rateio_unico_por_pessoa')],
            },
        ),
    ]
