# Generated by Django 6.0.8 on 2026-09-15 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carteira', '0004_transacao_pago_por_rateio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateioPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='percentual')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateio_padrao', to='accounts.espaco')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios_padrao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'divisão padrão',
                'verbose_name_plural': 'divisão padrão',
                'constraints': [models.UniqueConstraint(fields=('espaco', 'pessoa'), name='rateio_padrao_unico_por_pessoa')],
            },
        ),
    ]
