# Generated by Django 6.0.8 on 2026-09-15 02:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carteira', '0005_rateiopadrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('referencia', models.CharField(max_length=7, verbose_name='referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acertos', to='accounts.espaco')),
                ('quem_pagou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acertos_pagos', to=settings.AUTH_USER_MODEL)),
                ('quem_recebeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acertos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acertos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acerto',
                'verbose_name_plural': 'acertos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['espaco', 'referencia'], name='carteira_ac_espaco__10f6b1_idx')],
            },
        ),
    ]
