# Generated by Django 6.0.8 on 2026-09-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0006_acerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='grupo_parcela',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='grupo da parcela'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='parcela',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='parcela'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='total_parcelas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='total de parcelas'),
        ),
    ]
