# Generated by Django 6.0.8 on 2026-09-16 18:12

import bot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='chat id')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='@username')),
                ('primeiro_nome', models.CharField(blank=True, max_length=100, verbose_name='primeiro nome')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('bloqueado_em', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('onboarding_etapa', models.PositiveSmallIntegerField(default=0, verbose_name='etapa do onboarding')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_telegram', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conta do Telegram',
                'verbose_name_plural': 'contas do Telegram',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(default='console', max_length=20, verbose_name='canal')),
                ('direcao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='direção')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio'), ('imagem', 'Imagem'), ('documento', 'Documento'), ('sistema', 'Sistema')], default='texto', max_length=20, verbose_name='tipo')),
                ('id_externo', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='id externo')),
                ('texto', models.TextField(blank=True, verbose_name='texto')),
                ('transcricao', models.TextField(blank=True, verbose_name='transcrição')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('processando', 'Processando'), ('respondida', 'Respondida'), ('erro', 'Erro'), ('ignorada', 'Ignorada')], default='recebida', max_length=20, verbose_name='status')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='payload')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='bot.contatelegram')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=256, verbose_name='file id')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='mime type')),
                ('arquivo', models.FileField(upload_to='bot/%Y/%m/', verbose_name='arquivo')),
                ('tamanho', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('duracao_s', models.PositiveIntegerField(blank=True, null=True, verbose_name='duração (s)')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('mensagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='bot.mensagem')),
            ],
            options={
                'verbose_name': 'mídia',
                'verbose_name_plural': 'mídias',
            },
        ),
        migrations.CreateModel(
            name='CodigoPareamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=bot.models.gerar_codigo_pareamento, max_length=8, verbose_name='código')),
                ('token', models.CharField(default=bot.models.gerar_token_pareamento, max_length=64, unique=True, verbose_name='token do deep link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de pareamento',
                'verbose_name_plural': 'códigos de pareamento',
                'indexes': [models.Index(fields=['codigo', 'usado_em'], name='bot_codigop_codigo_23078f_idx'), models.Index(fields=['token', 'usado_em'], name='bot_codigop_token_61eca7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['conta', 'criada_em'], name='bot_mensage_conta_i_839f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['usuario', 'criada_em'], name='bot_mensage_usuario_73332d_idx'),
        ),
    ]
