# Generated by Django 6.0.8 on 2026-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remover_legado_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='turno',
            field=models.JSONField(blank=True, null=True, verbose_name='turno'),
        ),
    ]
