# Generated by Django 6.0.8 on 2026-09-14 22:33

import django.db.models.deletion
import zap.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(default='console', max_length=20, verbose_name='canal')),
                ('direcao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='direção')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio'), ('imagem', 'Imagem'), ('documento', 'Documento'), ('template', 'Template'), ('sistema', 'Sistema')], default='texto', max_length=20, verbose_name='tipo')),
                ('wamid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='wamid')),
                ('texto', models.TextField(blank=True, verbose_name='texto')),
                ('transcricao', models.TextField(blank=True, verbose_name='transcrição')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('processando', 'Processando'), ('respondida', 'Respondida'), ('erro', 'Erro'), ('ignorada', 'Ignorada')], default='recebida', max_length=20, verbose_name='status')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='payload')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(blank=True, max_length=128, verbose_name='media id')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='mime type')),
                ('arquivo', models.FileField(upload_to='zap/%Y/%m/', verbose_name='arquivo')),
                ('tamanho', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('duracao_s', models.PositiveIntegerField(blank=True, null=True, verbose_name='duração (s)')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('mensagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='zap.mensagem')),
            ],
            options={
                'verbose_name': 'mídia',
                'verbose_name_plural': 'mídias',
            },
        ),
        migrations.CreateModel(
            name='NumeroWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'número de WhatsApp',
                'verbose_name_plural': 'números de WhatsApp',
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='zap.numerowhatsapp'),
        ),
        migrations.CreateModel(
            name='JanelaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_inbound_em', models.DateTimeField(verbose_name='último inbound em')),
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='janela', to='zap.numerowhatsapp')),
            ],
            options={
                'verbose_name': 'janela de atendimento',
                'verbose_name_plural': 'janelas de atendimento',
            },
        ),
        migrations.CreateModel(
            name='CodigoPareamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=zap.models.gerar_codigo_pareamento, max_length=8, verbose_name='código')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de pareamento',
                'verbose_name_plural': 'códigos de pareamento',
                'indexes': [models.Index(fields=['codigo', 'usado_em'], name='zap_codigop_codigo_54233f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['numero', 'criada_em'], name='zap_mensage_numero__1ef895_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['usuario', 'criada_em'], name='zap_mensage_usuario_5c5932_idx'),
        ),
    ]
