# Generated by Django 6.0.8 on 2026-09-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerowhatsapp',
            name='onboarding_etapa',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='etapa do onboarding'),
        ),
    ]
